/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:c6bb184f-2720-4258-9743-8a8f707828fe",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_yPP8sdp3o",
    "aws_user_pools_web_client_id": "17qn7m3j6fn7i1lllg7ll2213a",
    "oauth": {}
};


export default awsmobile;
